### PR TITLE
Misc features

### PR DESCRIPTION
**Pull request by leonyeo**
Couple of misc features:
x button to clear autocomplete search bar
Whatsapp and Telegram share buttons

Currently the share buttons are placed at the bottom of the restaurants list, and updated whenver we choose a different restaurant. Would be good to get some input on where would be the best location for these buttons.

Currently telegram share link shares a placeholder link. This would be replaced with the link to google maps once that feature is completed.

https://lyeo-sps-summer20.appspot.com/

### CODE REVIEW

**Comment by jieliangang** [comment]
We can have an infowindow for the selected restaurant similar to the one on the chosen location, to display the restaurant info along with the social media sharing icons.

Also note that there is a small conflict with the recently merged PR.

**Comment by leonyeo** [comment]
Alright cool will wait for the infowindow to be merged and sort out the conflicts as well

**Comment by leonyeo** [comment]
Moved share buttons to infowindow

https://lyeo-sps-summer20.appspot.com/

**Comment by lolfuljames** [comment]
The 'x' still seems out of place and feels as though its overlapping with the text.

Reference:
image

I've experimented with this and I think setting the whole pac-card to flex (I did it in my PR here https://github.com/daekoon/EatGoWhere/pull/16/files#diff-494841b0b2395305cf87e3d10f6911eaR65) along with a few padding adjustments, will help with the placement. Could you give it a try and see if it helps?

**Comment by leonyeo** [comment]
Added a bit more padding, should be fixed now. Not too sure about setting it to flex?
https://lyeo-sps-summer20.appspot.com/

**Review by lolfuljames — APPROVED** [review]

**Comment by lolfuljames** [comment]
LGTM!

**Pull request merged**
