### PR TITLE
Update Mobile View Styling

### PR DESCRIPTION
**Pull request by jieliangang**
Website is now more mobile friendly.

Demo: https://jang-sps-summer20.appspot.com/

### CODE REVIEW

**Comment by daekoon** [comment]
I'm getting the following error when I try to submit a place:
```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
Promise.then (async)
(anonymous) @ script.js:91
Promise.then (async)
(anonymous) @ script.js:90
```
are you getting the same error?

**Comment by jieliangang** [comment]
> I'm getting the following error when I try to submit a place:
> 
> ```
> Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
> Promise.then (async)
> (anonymous) @ script.js:91
> Promise.then (async)
> (anonymous) @ script.js:90
> ```
> 
> are you getting the same error?

can you guide on how to reproduce the error?

**Comment by daekoon** [comment]
I did this:

1. Type any address in the search bar (I used `9 Toh Yi Drive, Singapore` for this, but it seems to work with other addresses as well)
2. Press submit

Expected behavior: One of the random restaurants is displayed
Actual behavior: Nothing. Console log shows the following error:
```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
Promise.then (async)
(anonymous) @ script.js:91
Promise.then (async)
(anonymous) @ script.js:90
```

**Comment by lolfuljames** [comment]
LGMT, chinese characters are still not showing, did you deploy your demo with the latest files? Let's wait for daekoon to confirm his findings before we approve it.

**Review by lolfuljames — COMMENTED** [review]
LGTM, let's get Daekoon to approve this PR.

**Comment by jieliangang** [comment]
Fixed view in mobile browser. Can test at my site.

**Review by lolfuljames — APPROVED** [review]
LGTM

**Pull request merged**
